//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StepCount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogEntry
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Select Participant")]
        [Range(1, int.MaxValue, ErrorMessage = "Select participant")]
        public int ParticipantId { get; set; }

        public Nullable<System.DateTime> LogDate { get; set; }
        public Nullable<int> Steps { get; set; }
    
        public virtual Participant Participant { get; set; }
    }
}
