//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace StepCount.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participant
    {
        public Participant()
        {
            this.LogEntries = new HashSet<LogEntry>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }

        [Required(ErrorMessage = "Team Id is required")]
        public Nullable<int> TeamId { get; set; }
    
        public virtual ICollection<LogEntry> LogEntries { get; set; }
        public virtual Team Team { get; set; }
    }
}
